### ISSUE TITLE
importError: cannot import name 'quote'

### ISSUE THREAD

**Issue by harishsg99** [llSourcell/AI_Startup_Prototype#8]
sing TensorFlow backend.
Traceback (most recent call last):
  File "manage.py", line 4, in <module>
    from app import app, db, models
  File "/home/harish/Desktop/my startup ideas and stuff/AI_Startup_Prototype-master (1)/AI_Startup_Prototype-master/flaskSaaS-master/app/__init__.py", line 46, in <module>
    from app import admin
  File "/home/harish/Desktop/my startup ideas and stuff/AI_Startup_Prototype-master (1)/AI_Startup_Prototype-master/flaskSaaS-master/app/admin.py", line 7, in <module>
    from flask.ext.admin.contrib.fileadmin import FileAdmin
  File "/home/harish/.local/lib/python3.6/site-packages/flask_admin/contrib/fileadmin/__init__.py", line 15, in <module>
    from flask_admin._compat import urljoin, as_unicode, quote
ImportError: cannot import name 'quote'

**Comment by harishsg99** [comment]
how to fix this?
im using ubuntu 18.04

**Comment by ghost** [comment]
i am using ubuntu 18.04
~$ python manage.py initdb
Traceback (most recent call last):
  File "manage.py", line 4, in <module>
    from app import app, db, models
  File "/home/AI_Startup_Prototype-master/flaskSaaS/app/__init__.py", line 30, in <module>
    from app.views import main, user, error
ImportError: No module named views
